// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230407114513_InitialUserRegistrationLogin")]
    partial class InitialUserRegistrationLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPI.Models.DeviceModel.DeviceModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<short?>("ADMISSON_LEVEL")
                        .HasColumnType("smallint");

                    b.Property<string>("DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("DOOR_CLOSE")
                        .HasColumnType("smallint");

                    b.Property<short?>("DOOR_OPEN")
                        .HasColumnType("smallint");

                    b.Property<short?>("DOOR_STATUS")
                        .HasColumnType("smallint");

                    b.Property<long>("IMEI")
                        .HasColumnType("bigint");

                    b.Property<short?>("LEFT_DOOR")
                        .HasColumnType("smallint");

                    b.Property<short?>("PING")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RECORDING_TIME")
                        .HasColumnType("datetime2");

                    b.Property<short?>("RIGHT_DOOR")
                        .HasColumnType("smallint");

                    b.Property<string>("STARTBYTE")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID");

                    b.ToTable("DoorInformationUPDATED");
                });

            modelBuilder.Entity("WebAPI.Models.DeviceModel.ListenerModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<short?>("ADMISSON_LEVEL")
                        .HasColumnType("smallint");

                    b.Property<string>("DATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("DOOR_CLOSE")
                        .HasColumnType("smallint");

                    b.Property<short?>("DOOR_OPEN")
                        .HasColumnType("smallint");

                    b.Property<short?>("DOOR_STATUS")
                        .HasColumnType("smallint");

                    b.Property<long>("IMEI")
                        .HasColumnType("bigint");

                    b.Property<short?>("LEFT_DOOR")
                        .HasColumnType("smallint");

                    b.Property<short?>("PING")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RECORDING_TIME")
                        .HasColumnType("datetime2");

                    b.Property<short?>("RIGHT_DOOR")
                        .HasColumnType("smallint");

                    b.Property<string>("STARTBYTE")
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("ID");

                    b.ToTable("DoorInformation");
                });

            modelBuilder.Entity("WebAPI.Models.DeviceModel.OrderHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Imei")
                        .HasColumnType("bigint");

                    b.Property<short>("InSent")
                        .HasColumnType("smallint");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrderResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderHistory");
                });

            modelBuilder.Entity("WebAPI.Models.DeviceModel.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebAPI.Models.UserModel.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
